name: HungerGames
version: '${project.version}'
main: me.thomas.hungergames.HungerGames
api-version: 1.13
authors: [ Thomas ]
description: Description

commands:
  kits:
  newspawn:
  game:
  chests:
  hgstats: